//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lextm.ArtCSB {
	using System;
	
	
	/// <summary>
	///   强类型资源类，用于查找本地化字符串等。
	/// </summary>
	// 此类是由 StronglyTypedResourceBuilder
	// 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
	// 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
	// (以 /str 作为命令选项)，或重新生成 VS 项目。
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class ArtCSB_MyResource {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal ArtCSB_MyResource() {
		}
		
		/// <summary>
		///   返回此类使用的缓存 ResourceManager 实例。
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lextm.ArtCSB.ArtCSB_MyResource", typeof(ArtCSB_MyResource).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   为使用此强类型资源类的所有资源查找
		///   重写当前线程的 CurrentUICulture 属性。
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		internal static System.Drawing.Bitmap _0_JPG {
			get {
				object obj = ResourceManager.GetObject("0.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _1_JPG {
			get {
				object obj = ResourceManager.GetObject("1.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _10_JPG {
			get {
				object obj = ResourceManager.GetObject("10.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _100_JPG {
			get {
				object obj = ResourceManager.GetObject("100.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _101_JPG {
			get {
				object obj = ResourceManager.GetObject("101.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _102_JPG {
			get {
				object obj = ResourceManager.GetObject("102.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _103_JPG {
			get {
				object obj = ResourceManager.GetObject("103.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _104_JPG {
			get {
				object obj = ResourceManager.GetObject("104.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _105_JPG {
			get {
				object obj = ResourceManager.GetObject("105.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _106_JPG {
			get {
				object obj = ResourceManager.GetObject("106.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _107_JPG {
			get {
				object obj = ResourceManager.GetObject("107.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _108_JPG {
			get {
				object obj = ResourceManager.GetObject("108.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _109_JPG {
			get {
				object obj = ResourceManager.GetObject("109.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _11_JPG {
			get {
				object obj = ResourceManager.GetObject("11.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _110_JPG {
			get {
				object obj = ResourceManager.GetObject("110.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _111_JPG {
			get {
				object obj = ResourceManager.GetObject("111.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _112_JPG {
			get {
				object obj = ResourceManager.GetObject("112.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _113_JPG {
			get {
				object obj = ResourceManager.GetObject("113.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _114_JPG {
			get {
				object obj = ResourceManager.GetObject("114.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _115_JPG {
			get {
				object obj = ResourceManager.GetObject("115.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _116_JPG {
			get {
				object obj = ResourceManager.GetObject("116.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _117_JPG {
			get {
				object obj = ResourceManager.GetObject("117.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _118_JPG {
			get {
				object obj = ResourceManager.GetObject("118.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _12_JPG {
			get {
				object obj = ResourceManager.GetObject("12.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _13_JPG {
			get {
				object obj = ResourceManager.GetObject("13.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _14_JPG {
			get {
				object obj = ResourceManager.GetObject("14.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _15_JPG {
			get {
				object obj = ResourceManager.GetObject("15.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _16_JPG {
			get {
				object obj = ResourceManager.GetObject("16.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _17_JPG {
			get {
				object obj = ResourceManager.GetObject("17.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _18_JPG {
			get {
				object obj = ResourceManager.GetObject("18.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _19_JPG {
			get {
				object obj = ResourceManager.GetObject("19.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _2_JPG {
			get {
				object obj = ResourceManager.GetObject("2.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _20_JPG {
			get {
				object obj = ResourceManager.GetObject("20.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _21_JPG {
			get {
				object obj = ResourceManager.GetObject("21.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _22_JPG {
			get {
				object obj = ResourceManager.GetObject("22.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _23_JPG {
			get {
				object obj = ResourceManager.GetObject("23.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _24_JPG {
			get {
				object obj = ResourceManager.GetObject("24.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _25_JPG {
			get {
				object obj = ResourceManager.GetObject("25.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _26_JPG {
			get {
				object obj = ResourceManager.GetObject("26.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _27_JPG {
			get {
				object obj = ResourceManager.GetObject("27.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _28_JPG {
			get {
				object obj = ResourceManager.GetObject("28.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _29_JPG {
			get {
				object obj = ResourceManager.GetObject("29.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _3_JPG {
			get {
				object obj = ResourceManager.GetObject("3.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _30_JPG {
			get {
				object obj = ResourceManager.GetObject("30.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _31_JPG {
			get {
				object obj = ResourceManager.GetObject("31.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _32_JPG {
			get {
				object obj = ResourceManager.GetObject("32.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _33_JPG {
			get {
				object obj = ResourceManager.GetObject("33.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _34_JPG {
			get {
				object obj = ResourceManager.GetObject("34.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _35_JPG {
			get {
				object obj = ResourceManager.GetObject("35.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _36_JPG {
			get {
				object obj = ResourceManager.GetObject("36.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _37_JPG {
			get {
				object obj = ResourceManager.GetObject("37.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _38_JPG {
			get {
				object obj = ResourceManager.GetObject("38.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _39_JPG {
			get {
				object obj = ResourceManager.GetObject("39.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _4_JPG {
			get {
				object obj = ResourceManager.GetObject("4.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _40_JPG {
			get {
				object obj = ResourceManager.GetObject("40.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _41_JPG {
			get {
				object obj = ResourceManager.GetObject("41.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _42_JPG {
			get {
				object obj = ResourceManager.GetObject("42.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _43_JPG {
			get {
				object obj = ResourceManager.GetObject("43.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _44_JPG {
			get {
				object obj = ResourceManager.GetObject("44.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _45_JPG {
			get {
				object obj = ResourceManager.GetObject("45.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _46_JPG {
			get {
				object obj = ResourceManager.GetObject("46.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _47_JPG {
			get {
				object obj = ResourceManager.GetObject("47.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _48_JPG {
			get {
				object obj = ResourceManager.GetObject("48.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _49_JPG {
			get {
				object obj = ResourceManager.GetObject("49.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _5_JPG {
			get {
				object obj = ResourceManager.GetObject("5.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _50_JPG {
			get {
				object obj = ResourceManager.GetObject("50.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _51_JPG {
			get {
				object obj = ResourceManager.GetObject("51.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _52_JPG {
			get {
				object obj = ResourceManager.GetObject("52.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _53_JPG {
			get {
				object obj = ResourceManager.GetObject("53.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _54_JPG {
			get {
				object obj = ResourceManager.GetObject("54.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _55_JPG {
			get {
				object obj = ResourceManager.GetObject("55.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _56_JPG {
			get {
				object obj = ResourceManager.GetObject("56.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _57_JPG {
			get {
				object obj = ResourceManager.GetObject("57.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _58_JPG {
			get {
				object obj = ResourceManager.GetObject("58.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _59_JPG {
			get {
				object obj = ResourceManager.GetObject("59.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _6_JPG {
			get {
				object obj = ResourceManager.GetObject("6.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _60_JPG {
			get {
				object obj = ResourceManager.GetObject("60.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _61_JPG {
			get {
				object obj = ResourceManager.GetObject("61.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _62_JPG {
			get {
				object obj = ResourceManager.GetObject("62.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _63_JPG {
			get {
				object obj = ResourceManager.GetObject("63.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _64_JPG {
			get {
				object obj = ResourceManager.GetObject("64.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _65_JPG {
			get {
				object obj = ResourceManager.GetObject("65.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _66_JPG {
			get {
				object obj = ResourceManager.GetObject("66.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _67_JPG {
			get {
				object obj = ResourceManager.GetObject("67.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _68_JPG {
			get {
				object obj = ResourceManager.GetObject("68.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _69_JPG {
			get {
				object obj = ResourceManager.GetObject("69.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _7_JPG {
			get {
				object obj = ResourceManager.GetObject("7.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _70_JPG {
			get {
				object obj = ResourceManager.GetObject("70.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _71_JPG {
			get {
				object obj = ResourceManager.GetObject("71.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _72_JPG {
			get {
				object obj = ResourceManager.GetObject("72.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _73_JPG {
			get {
				object obj = ResourceManager.GetObject("73.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _74_JPG {
			get {
				object obj = ResourceManager.GetObject("74.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _75_JPG {
			get {
				object obj = ResourceManager.GetObject("75.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _76_JPG {
			get {
				object obj = ResourceManager.GetObject("76.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _77_JPG {
			get {
				object obj = ResourceManager.GetObject("77.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _78_JPG {
			get {
				object obj = ResourceManager.GetObject("78.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _79_JPG {
			get {
				object obj = ResourceManager.GetObject("79.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _8_JPG {
			get {
				object obj = ResourceManager.GetObject("8.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _80_JPG {
			get {
				object obj = ResourceManager.GetObject("80.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _81_JPG {
			get {
				object obj = ResourceManager.GetObject("81.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _82_JPG {
			get {
				object obj = ResourceManager.GetObject("82.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _83_JPG {
			get {
				object obj = ResourceManager.GetObject("83.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _84_JPG {
			get {
				object obj = ResourceManager.GetObject("84.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _85_JPG {
			get {
				object obj = ResourceManager.GetObject("85.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _86_JPG {
			get {
				object obj = ResourceManager.GetObject("86.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _87_JPG {
			get {
				object obj = ResourceManager.GetObject("87.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _88_JPG {
			get {
				object obj = ResourceManager.GetObject("88.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _89_JPG {
			get {
				object obj = ResourceManager.GetObject("89.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _9_JPG {
			get {
				object obj = ResourceManager.GetObject("9.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _90_JPG {
			get {
				object obj = ResourceManager.GetObject("90.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _91_JPG {
			get {
				object obj = ResourceManager.GetObject("91.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _92_JPG {
			get {
				object obj = ResourceManager.GetObject("92.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _93_JPG {
			get {
				object obj = ResourceManager.GetObject("93.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _94_JPG {
			get {
				object obj = ResourceManager.GetObject("94.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _95_JPG {
			get {
				object obj = ResourceManager.GetObject("95.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _96_JPG {
			get {
				object obj = ResourceManager.GetObject("96.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _97_JPG {
			get {
				object obj = ResourceManager.GetObject("97.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _98_JPG {
			get {
				object obj = ResourceManager.GetObject("98.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap _99_JPG {
			get {
				object obj = ResourceManager.GetObject("99.JPG", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   查找类似 {\rtf1\ansi\ansicpg1251\uc1\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049{\fonttbl{\f0\froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}
		///{\f1\fswiss\fcharset204\fprq2{\*\panose 020b0604020202020204}Arial;}{\f3\froman\fcharset2\fprq2{\*\panose 05050102010706020507}Symbol;}{\f198\froman\fcharset0\fprq2 Times New Roman;}{\f196\froman\fcharset238\fprq2 Times New Roman CE;}
		///{\f199\froman\fcharset161\fprq2 Times New Roman Greek;}{\f200\froman\fcharset162\fprq2 [字符串的其余部分被截断]&quot;; 的本地化字符串。
		/// </summary>
		internal static string ArtCSB_rtf {
			get {
				return ResourceManager.GetString("ArtCSB.rtf", resourceCulture);
			}
		}
		
		internal static System.Drawing.Bitmap ArtCSB24x24_bmp {
			get {
				object obj = ResourceManager.GetObject("ArtCSB24x24.bmp", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap ArtCSB36x36_bmp {
			get {
				object obj = ResourceManager.GetObject("ArtCSB36x36.bmp", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Icon AutoSave16x16_ico {
			get {
				object obj = ResourceManager.GetObject("AutoSave16x16.ico", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
		
		internal static System.Drawing.Icon DesignerNavigator16x16_ico {
			get {
				object obj = ResourceManager.GetObject("DesignerNavigator16x16.ico", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
		
		internal static System.Drawing.Icon elide_current16x16_ico {
			get {
				object obj = ResourceManager.GetObject("elide_current16x16.ico", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
		
		internal static System.Drawing.Icon elide_methods16x16_ico {
			get {
				object obj = ResourceManager.GetObject("elide_methods16x16.ico", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
		
		internal static System.Drawing.Icon SourceNavigator16x16_ico {
			get {
				object obj = ResourceManager.GetObject("SourceNavigator16x16.ico", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
		
		internal static System.Drawing.Icon unelide_all16x16_ico {
			get {
				object obj = ResourceManager.GetObject("unelide_all16x16.ico", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
		
		internal static System.Drawing.Icon unelide_current16x16_ico {
			get {
				object obj = ResourceManager.GetObject("unelide_current16x16.ico", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
		
		internal static System.Drawing.Icon UnknownImage16x16_ico {
			get {
				object obj = ResourceManager.GetObject("UnknownImage16x16.ico", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
		
		internal static System.Drawing.Icon view_source16x16_ico {
			get {
				object obj = ResourceManager.GetObject("view_source16x16.ico", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
	}
}
