//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZetaLib.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZetaLib.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You passed a file-name-only (&apos;{ConnectionString}&apos;) as the connection string to CompactJetDatabase(). Please use the FileInfo-overload instead..
        /// </summary>
        internal static string Str_AdoNetOleDBHelper_CompactJetDatabase_Error01 {
            get {
                return ResourceManager.GetString("Str_AdoNetOleDBHelper_CompactJetDatabase_Error01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified source file path &apos;{SourceFilePath}&apos; path does not exists..
        /// </summary>
        internal static string Str_AdoNetOleDBHelper_CompactJetDatabase_Error02 {
            get {
                return ResourceManager.GetString("Str_AdoNetOleDBHelper_CompactJetDatabase_Error02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You passed a file-name-only (&apos;{ConnectionString}&apos;) as the connection string to RefreshJetCache(). Please use the FileInfo-overload instead!.
        /// </summary>
        internal static string Str_AdoNetOleDBHelper_CompactJetDatabase_Error03 {
            get {
                return ResourceManager.GetString("Str_AdoNetOleDBHelper_CompactJetDatabase_Error03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid folder path for the deleted files! Currently &apos;{FolderPath}&apos; is specified..
        /// </summary>
        internal static string Str_FileDeleteHelper_Error01 {
            get {
                return ResourceManager.GetString("Str_FileDeleteHelper_Error01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bytes.
        /// </summary>
        internal static string Str_FormatFileSize_Bytes {
            get {
                return ResourceManager.GetString("Str_FormatFileSize_Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string Str_FormatFileSize_GB {
            get {
                return ResourceManager.GetString("Str_FormatFileSize_GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kB.
        /// </summary>
        internal static string Str_FormatFileSize_KB {
            get {
                return ResourceManager.GetString("Str_FormatFileSize_KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string Str_FormatFileSize_MB {
            get {
                return ResourceManager.GetString("Str_FormatFileSize_MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TB.
        /// </summary>
        internal static string Str_FormatFileSize_TB {
            get {
                return ResourceManager.GetString("Str_FormatFileSize_TB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging could not be configured. Please ensure to call ZetaLib.CoreLibraryConfiguration.Current.Initialize() once at the very start of your application, before doing any logging functions, if you are running a web application, a good place would be inside GLOBAL.ASAX. If you are running a Windows application, you usually do that right at the start of the MAIN function..
        /// </summary>
        internal static string Str_LogCentral_Error01 {
            get {
                return ResourceManager.GetString("Str_LogCentral_Error01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A maximum of one default task may be specified, but there are {Count} default tasks specified..
        /// </summary>
        internal static string Str_ZetaLib_Core_Base_Tasks_TaskBase_DispatchTasks_01 {
            get {
                return ResourceManager.GetString("Str_ZetaLib_Core_Base_Tasks_TaskBase_DispatchTasks_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter.
        /// </summary>
        internal static string Str_ZetaLib_Core_Caching_CacheItemInformation_01 {
            get {
                return ResourceManager.GetString("Str_ZetaLib_Core_Caching_CacheItemInformation_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LDAP server was not specified..
        /// </summary>
        internal static string Str_ZetaLib_Core_Common_ActiveDirectory_01 {
            get {
                return ResourceManager.GetString("Str_ZetaLib_Core_Common_ActiveDirectory_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with GUID &apos;{Guid}&apos; not found in Active Directory..
        /// </summary>
        internal static string Str_ZetaLib_Core_Common_ActiveDirectory_02 {
            get {
                return ResourceManager.GetString("Str_ZetaLib_Core_Common_ActiveDirectory_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name must be provided and cannot be null..
        /// </summary>
        internal static string Str_ZetaLib_Core_Common_Dump_01 {
            get {
                return ResourceManager.GetString("Str_ZetaLib_Core_Common_Dump_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name must be provided and cannot be empty..
        /// </summary>
        internal static string Str_ZetaLib_Core_Common_Dump_02 {
            get {
                return ResourceManager.GetString("Str_ZetaLib_Core_Common_Dump_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file extension must be specified..
        /// </summary>
        internal static string Str_ZetaLib_Core_Common_Misc_FileExtensionRegistration_01 {
            get {
                return ResourceManager.GetString("Str_ZetaLib_Core_Common_Misc_FileExtensionRegistration_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info.ClassName must be non-empty..
        /// </summary>
        internal static string Str_ZetaLib_Core_Common_Misc_FileExtensionRegistration_02 {
            get {
                return ResourceManager.GetString("Str_ZetaLib_Core_Common_Misc_FileExtensionRegistration_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info.Description must be non-empty..
        /// </summary>
        internal static string Str_ZetaLib_Core_Common_Misc_FileExtensionRegistration_03 {
            get {
                return ResourceManager.GetString("Str_ZetaLib_Core_Common_Misc_FileExtensionRegistration_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info.ApplicationFilePath must be non-empty..
        /// </summary>
        internal static string Str_ZetaLib_Core_Common_Misc_FileExtensionRegistration_04 {
            get {
                return ResourceManager.GetString("Str_ZetaLib_Core_Common_Misc_FileExtensionRegistration_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application registry key was not set..
        /// </summary>
        internal static string Str_ZetaLib_Core_Common_Storage_01 {
            get {
                return ResourceManager.GetString("Str_ZetaLib_Core_Common_Storage_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter value must be of type P..
        /// </summary>
        internal static string Str_ZetaLib_Core_Data_AdoNetBaseHelper_01 {
            get {
                return ResourceManager.GetString("Str_ZetaLib_Core_Data_AdoNetBaseHelper_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Database type: &apos;{Type}&apos;..
        /// </summary>
        internal static string Str_ZetaLib_Core_Data_AdoNetOdbcHelper_01 {
            get {
                return ResourceManager.GetString("Str_ZetaLib_Core_Data_AdoNetOdbcHelper_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Database type: &apos;{Type}&apos;..
        /// </summary>
        internal static string Str_ZetaLib_Core_Data_AdoNetOleDBHelper_01 {
            get {
                return ResourceManager.GetString("Str_ZetaLib_Core_Data_AdoNetOleDBHelper_01", resourceCulture);
            }
        }
    }
}
