
/// <summary>
/// CSharp NUnit Test Case
/// This unit contains a skeleton test case class generated by the Test Case Wizard.
/// Modify the generated code to correctly setup and call the methods from the unit being tested.
/// </summary>

namespace TestThirdParty
{
    using System;
    using System.Collections;
    using System.ComponentModel;
    using NUnit.Framework;
	using pglowacki.XmlDoc;
	using System.Windows.Forms;



	// Test methods for class FormXmlDocViewer
	[TestFixture]
	public class TestFormXmlDocViewer
	{
		
		private FormXmlDocViewer formXmlDocViewer;
		
		[SetUp]
		public void SetUp()
		{

		}
		
		[TearDown]
		public void TearDown()
		{
		}
		
		[Test]
		public void TestDisplayHtml()
		{
			string s = "<body>Test only.</body>";
			// TODO: Setup method call parameters
			formXmlDocViewer = new FormXmlDocViewer();
			formXmlDocViewer.DisplayHtml(s);
            formXmlDocViewer.ShowDialog();
			// TODO: Validate method results
			Assert.AreEqual(DialogResult.Yes,
				MessageBox.Show("do you see test only", "??",
					MessageBoxButtons.YesNo));
		}
	}
}
