/// <summary>
/// CSharp NUnit Test Case
/// This unit contains a skeleton test case class generated by the Test Case Wizard.
/// Modify the generated code to correctly setup and call the methods from the unit being tested.
/// </summary>

namespace TestFramework
{                                        

	using System;
	using System.Collections;
	using System.ComponentModel;
	using NUnit.Framework;
	using Lextm.CodeBeautifierCollection.Collections;
	
	// Test methods for class OtaUtils
	[TestFixture]
	public class TestTabTree
	{
		private TabBuilder tt;
		[SetUp]
		public void SetUp()
		{
			tt = TabBuilder.getInstance();
		}

		[TearDown]
		public void TearDown()
		{

		}

		[Test]
		public void TestRegister()
		{
//			tt.Build((IOtaFramework)OtaArrayList.getInstance()[0]);
			Console.Out.WriteLine(tt.NodeCount.ToString());
			Assert.AreEqual(1, tt.NodeCount);
		}
	}
}
