
/// <summary>
/// CSharp NUnit Test Case
/// This unit contains a skeleton test case class generated by the Test Case Wizard.
/// Modify the generated code to correctly setup and call the methods from the unit being tested.
/// </summary>

namespace TestWiseEditor
{
    using System;
    using System.Collections;
    using System.ComponentModel;
    using System.Data;
    using NUnit.Framework;
	using Lextm.WiseEditor.Gui;
    using System.Windows.Forms;


	// Test methods for class FormComponentName
	[TestFixture]
	public class TestFormComponentName
	{
		
		private FormComponentName formComponentName;
		
		[SetUp]
		public void SetUp()
		{
			formComponentName = new FormComponentName();
		}
		
		[TearDown]
		public void TearDown()
		{
			formComponentName = null;
		}
		
		[Test]
		public void TestgetInstance()
		{
			FormComponentName returnValue;
			returnValue = formComponentName;
			returnValue.txtName.Text = "name";
			DialogResult result = returnValue.ShowDialog();
			// TODO: Validate method results
			Assert.AreEqual("name", returnValue.txtName.Text);
            Assert.AreEqual(DialogResult.OK, result);
		}
	}
}
