
/// <summary>
/// CSharp NUnit Test Case
/// This unit contains a skeleton test case class generated by the Test Case Wizard.
/// Modify the generated code to correctly setup and call the methods from the unit being tested.
/// </summary>

namespace TestFramework
{
    using System;
    using System.Collections;
    using System.ComponentModel;
    using System.Data;
    using NUnit.Framework;
	using Lextm.CodeBeautifierCollection.Gui;
	using System.Windows.Forms;



	// Test methods for class FormAbout
	[TestFixture]
	public class TestFormAbout
	{
		
		//private FormAbout formAbout;
		
		[SetUp]
		public void SetUp()
		{
		}

		[TearDown]
		public void TearDown()
		{
		}

		[Test]
		public void TestgetInstance()
		{
			FormAbout returnValue;
			returnValue = new FormAbout();
			returnValue.ShowDialog();
			// TODO: Validate method results
			Assert.AreEqual(DialogResult.Yes,
				MessageBox.Show("do you see the about",
					"??", MessageBoxButtons.YesNo));
		}
	}
}
