//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.288
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by xsd, Version=1.0.3705.288.
//
using System.Xml.Serialization;


/// <remarks/>
[System.Xml.Serialization.XmlRootAttribute("test-results", Namespace="", IsNullable=false)]
public class resultType {

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("test-suite")]
    public testsuiteType testsuite;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.Decimal total;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.Decimal failures;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("not-run")]
    public System.Decimal notrun;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string date;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string time;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(TypeName="test-suiteType")]
public class testsuiteType {

    /// <remarks/>
    public resultsType results;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string success;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string time;
}

/// <remarks/>
public class resultsType {

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("test-suite", typeof(testsuiteType))]
    [System.Xml.Serialization.XmlElementAttribute("test-case", typeof(testcaseType))]
    public object[] Items;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(TypeName="test-caseType")]
public class testcaseType {

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("failure", typeof(failureType))]
    [System.Xml.Serialization.XmlElementAttribute("reason", typeof(reasonType))]
    public object Item;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string success;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string time;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string executed;
}

/// <remarks/>
public class failureType {

    /// <remarks/>
    public string message;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("stack-trace")]
    public string stacktrace;
}

/// <remarks/>
public class reasonType {

    /// <remarks/>
    public string message;
}

